name: recipe_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_links: ^3.4.3
  cupertino_icons: ^1.0.2
  go_router: ^7.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  get_it: ^7.6.0
  shared_preferences: ^2.1.2
  injectable: ^2.1.2
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.5
  injectable_generator: ^2.1.2
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/json/

